### PR TITLE
Resolve some rpmlint issue and dir conflicts in SPEC.

### PR DESCRIPTION
**Pull request by sztsian**
Signed-off-by: Ziqian SUN (Zamir) <zsun@redhat.com>

### CODE REVIEW

**Comment by sztsian** [comment]
Hi,
This pull request aims at fix some outstanding rpmlint issue, as well as get rid of the error in RHEL
> file /usr/bin from install of lcov-1.11-1.noarch conflicts with file from package filesystem-3.2-21.el7.x86_64

There are remining rpmlint error that I did not fix here

>lcov.noarch: E: incorrect-fsf-address /usr/bin/genpng
lcov.noarch: E: incorrect-fsf-address /usr/bin/lcov
lcov.noarch: E: incorrect-fsf-address /usr/bin/geninfo
lcov.noarch: E: incorrect-fsf-address /usr/bin/gendesc
lcov.noarch: E: incorrect-fsf-address /usr/bin/genhtml

So if you think it is good to fix, I can do it.

**Comment by oberpar** [comment]
Changes look good except for the ones in the %files section. The RHEL error message mentioned has already been fixed with commit 68320d932c5ee5537ae1c287fe52603ae2fecf8c. Also the explicit .gz suffix will likely cause problems when a distribution has man page compression disabled or uses a different algorithm + suffix.

Lastly please submit your patch via e-mail to ltp-coverage@lists.sourceforge.net (see also https://github.com/linux-test-project/lcov/blob/master/CONTRIBUTING). Thanks!

**Comment by sztsian** [comment]
Thanks. I will rebase the changes according to the CONTRIBUTING guide as well as your suggestions later on.

**Comment by sztsian** [comment]
I find I cannot receive confirming email of subscribe to the mailing list. So I send the patch to the list with your working email copied. HTH.

**Comment by sztsian** [comment]
Fixed by commit b6a11368c3cdc86c4e147ccd8e539918dfe37900

**Pull request closed without merging**
