### PR TITLE
Support native Windows host

### PR DESCRIPTION
**Pull request by Farigh**
I've been working for a few years on a native Windows environment project.
We are using a gcc cross-compiler on Windows to build programs for our Linux target.

We added coverage and I had to make some modifications to LCOV so it can run natively on Windows through it's cmd.

Our toolchain being also a native Windows one, our coverage path contains Windows directory separators.

This PR contains all the necessary changes for LCOV to work natively on Windows

### CODE REVIEW

**Comment by Farigh** [comment]
By the way, I also noticed while running tests on Linux, to ensure no regression was introduced, that the `lcov_diff_apply` is broken, even on the `master` branch

**Comment by Farigh** [comment]
All tests are now passing : 
```shell
$ make test
Starting tests
genhtml/full.sh ................... [pass] (time 0.4s, mem 11.8MB)
genhtml/part1.sh .................. [pass] (time 0.1s, mem 11.6MB)
genhtml/part2.sh .................. [pass] (time 0.1s, mem 11.7MB)
genhtml/target.sh ................. [pass] (time 0.1s, mem 11.6MB)
genhtml/zero.sh ................... [pass] (time 0.1s, mem 11.7MB)
genhtml/demangle.sh ............... [pass] (time 0.3s, mem 11.2MB)
lcov/add/zero.sh .................. [pass] (time 0.2s, mem 11.5MB)
lcov/add/zero2.sh ................. [pass] (time 0.2s, mem 12.7MB)
lcov/add/full.sh .................. [pass] (time 0.1s, mem 11.7MB)
lcov/add/full2.sh ................. [pass] (time 0.2s, mem 12.7MB)
lcov/add/part.sh .................. [pass] (time 0.1s, mem 11.8MB)
lcov/add/part2.sh ................. [pass] (time 0.2s, mem 12.6MB)
lcov/add/concatenated4.sh ......... [pass] (time 0.2s, mem 12.3MB)
lcov/diff/test.sh ................. [pass] (time 0.1s, mem 10.10MB)
lcov/misc/help.sh ................. [pass] (time 0.0s, mem 10.8MB)
lcov/misc/version.sh .............. [pass] (time 0.0s, mem 10.8MB)
lcov/summary/zero.sh .............. [pass] (time 0.0s, mem 11.6MB)
lcov/summary/full.sh .............. [pass] (time 0.0s, mem 11.7MB)
lcov/summary/target.sh ............ [pass] (time 0.0s, mem 11.6MB)
lcov/summary/part1.sh ............. [pass] (time 0.0s, mem 11.6MB)
lcov/summary/part2.sh ............. [pass] (time 0.0s, mem 11.6MB)
lcov/summary/concatenated.sh ...... [pass] (time 0.1s, mem 11.8MB)
lcov/summary/concatenated2.sh ..... [pass] (time 0.1s, mem 11.9MB)
23 tests executed, 23 passed, 0 failed, 0 skipped (time 3.6s, mem 269.9MB)

```

**Comment by GitMensch** [comment]
That looks nice, can you please update this to current master (resolving the conflicts)? One thing that seems missing is the addition of the in-file ChangeLog entries, but this seems like a minor thing only.

If this is not included here for whatever reason it could be included as MSYS2 mingw package.

**Comment by GitMensch** [comment]
@Farigh Could you please rebase / fix the conflicts?

**Comment by GitMensch** [comment]
note: re-did the work with adjustments on current version, see #155

Definitely missing (but should be done in another PR): perl call in version output (installed versions don't have that any more).

**Comment by Farigh** [comment]
> note: re-did the work with adjustments on current version, see #155
> 
> Definitely missing (but should be done in another PR): perl call in version output (installed versions don't have that any more).

Thanks, I did not have time to look at it this past week.

I'll consider rebasing in the following weeks though, if still needed

**Comment by Farigh** [comment]
It looks good to me as is. Although I did not have time to test it on my professional project to try it.

I noticed you did not take some parts that would be necessary on a pure Windows environment like the find syscall (since the Windows find binary is quite different from the Linux one). I might open an additional PR once yours merged, for that purpose

**Comment by henry2cox** [comment]
Hi -
I fear that merging #169 may have introduced more windows compatibility issues (sorry about that!) - but also creates a bunch of merge conflicts with this PR.
Could you merge to current master and update this PR?  I will ensure that it gets merged quickly, after that.
Thanks!
Henry

**Comment by Farigh** [comment]
It might be easier to merge #155 first, since this PR is quite old.
I'll try to backport the other parts then

**Comment by GitMensch** [comment]
Sadly I'm out of time to handle that myself (I'm very non-fluid in writing perl and the C/C++ and COBOL projects are quite demanding currently). Maybe someone can re-apply #155 "from scratch"?

**Comment by henry2cox** [comment]
> It might be easier to merge #155 first, since this PR is quite old. I'll try to backport the other parts then

I think that most or all of the changes from #155 have been added to current TOT, and I know that Peter is in the process of cleaning up/assembling an "lcov 2.0" release - so now would be a Good Time to take a look at the current implementation and see what else needs to be fixed to support windows natively.

**Comment by henry2cox** [comment]
Closing this PR as there has been no action in 1.5 years and the work needs to be redone to catch up with lcov/2.0 and later changes - which have quite radically changed the code.

If anyone is still interested: please reopen this PR with an updated set of changes - and I will merge.
Please consider how to test on windows; it is likely that the regression suite and test driver will need some enhancement.
Henry

**Pull request closed without merging**
