### PR TITLE
Add a dark mode option

### PR DESCRIPTION
**Pull request by schmidtw**
This adds the update to the CSS and pngs needed to make the website for
a project so lcov can support both normal & 'dark mode' with the
--dark-mode command line option.

Signed-off-by: Weston Schmidt <Weston_Schmidt@alumni.purdue.edu>

### CODE REVIEW

**Comment by schmidtw** [comment]
@oberpar any thoughts on if you'd consider a dark mode option?

**Comment by henry2cox** [comment]
What is “dark mode”?

You can override the CSS file, if you want different colours.
Maybe you are looking for something more/something else?

Henry

**Comment by schmidtw** [comment]
"dark mode" is a color scheme with a generally dark/black background.  It's similar to what [github](https://github.com/settings/appearance) & others have.  The idea is to help reduce eye strain due to looking at a bright screen with dark text.

It is basically a change to the CSS, but the images generated also needs to be updated as well.

A few example screen shots:
image

image

**Comment by henry2cox** [comment]
Those screen shots appear to be the color scheme you wanted…
What changes did you make to the CSS?  And what other changes were required?  Or did you get what you show, strictly by overriding the CSS?
(This looks not hard to do – just wondering what is necessary to change.)

I guess you are looking for a “--dark” genhtml option, which would set things up for you (?)

Henry

**Comment by xaizek** [comment]
@henry2cox, this is not an issue, it's a PR.

**Comment by henry2cox** [comment]
Sorry – what is a “PR”?

I think I was saying that this seems like a pretty simple enhancement – though maybe some part is more complicated than I think.

Interestingly enough:  long back, there was _exactly_ the same discussion about background color and eye strain – only then, it was exactly the inverse of your request.  Strong suggestion was to go with dark on light background (like printed book) rather than light on dark background (like VDT of the day).
I haven’t done any reading lately, to see what current thinking is.

Henry

**Comment by xaizek** [comment]
PR stands for pull request.

**Comment by henry2cox** [comment]
Ah –

Sorry – my mistake.  (Obviously:  ignore everything I said.)

Henry

**Comment by oberpar** [comment]
I like the proposed new option to easily switch between two color schemes that serve different use cases. The implementation looks good, though you missed the colors that are used by `genpng` when creating overview images. But that's something that could be added by a follow-on patch if wanted.

Applied - thank you for your contribution. 

P.S.: Sorry for the delay when reviewing this feature, but I'm still hoping to get @henry2cox major feature branch merged somehow and anything that changes the base will make that more complicated. But I guess since this is an isolated change the added work should be negligible.

**Comment by henry2cox** [comment]
Tell you what…I’ll go ahead and merge all the changes/features which are on the master branch into my branch/my repo – then you can re-review.

I guess that merging the other changes is a Good Idea – even if the differential coverage and binning support never makes it into master.  My users might want it – or might use it, if they had it.

Henry

**Comment by henry2cox** [comment]
FWIW:  when I merged the ‘dark-mode’ changes to my branch, I also updated the PNG generation to use the dark colour scheme, added an entry to the man page, and added a couple of tests for the ‘dark mode’ feature.

I rather strongly suspect that there is a better ‘dark’ colour scheme than the one I’m currently using (copied from what was in the change, and then simply swapping foreground/background for any new colours that I had added, or anything that had not been updated in the genpng script).

Perhaps someone with a better colour sense than me could suggest a palette.

Henry

**Comment by schmidtw** [comment]
Yeah, I agree - I'm not a designer.  I tried to group the different color uses so it would be easier to follow up & change colors later.  Thanks for merging :).

One "gotcha" I ran into was how the PNG pixels come into existence.  They are binary blobs in the perl script & so changing the color palette doesn't adjust those.  I don't personally use the image on the right very often & forgot about it.

Maybe there is a way to generates the CSS focused PNGs?  Just an idea.

**Comment by henry2cox** [comment]
I had the same idea (have the PNG reflect the CSS in use).
Without changing this from static to dynamic HTML (javascript, HTML5, or whatever) – I don’t think I know how to do it.
I think it isn’t too hard to generate two PNGs and select between them from the CSS (…but I didn’t implement that/I think it is of limited utility at best).
The static HTML assumption is that all the pages and all the data is essentially there and read-only.
If we _did_ generate the views on-the-fly – then some other quite useful features would become possible..but that is also a fair bit of work.

Ah well – maybe someone who knows more than me can come up with a better solution.
Or – we somehow lived with the limitation (and no ‘dark’ mode) up to now…so maybe we will survive.

Henry

**Comment by henry2cox** [comment]
Ø   I don't personally use the image on the right very often & forgot about it.

BTW:  not sure if anyone else noticed – but there is a bug in firefox and chrome (and maybe other browsers as well) such that you can’t navigate to an anchor in a frame.  The link takes you to the top of the page containing the frame – not to a location in the frame.
I was not able to find a workaround.  (They all seem to require javascript – no way with static pages.)

What that means is that, if you use genhtml with frames (so you get the PNG navigation window on the left of the source-code detail window) then you can’t click on a link in that file’s parent ‘directory’ table (say, to go to the first UNC line in the file).

As a result – you have a decision to make:

-          you can use frames and PNG navigation – in which case, you have to go to the source page before you can navigate to lines/branches/functions that might interest you, OR

-          you can not use frames – and be able to navigate particular coverpoints with less clicking, but be unable to quickly scroll around to colored areas of interest.

If someone knows how to make this work correctly – please let me know (or simply update the code).

Henry

**Comment by henry2cox** [comment]
Another thought came to me:  it would be possible to add options (either RC, command line, or both) to let the user specify the PNG files as well.
Then, they could use whatever palette they want when they specify the CSS.

My rather strong suspicion is that no one overrides the defaults, though – so I don’t think this is worth implementing (or testing).

**Comment by jespertheend** [comment]
You could also use the [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) css media query to automatically use the color scheme as set by the users preferences. The only downside is that systems without a preference like this won't be able to configure the color scheme easily. But maybe you could work around that issue by making it possible to force a specific color scheme via a command line flag.

As for the pngs, I think you could just get rid of them entirely and set the bars using css only. That would eliminate the need to generate multiple pngs.

**Pull request merged**
