### PR TITLE
genhtml: support a comma separated list of prefixes

### PR DESCRIPTION
**Pull request by ggouaillardet**
Signed-off-by: Gilles Gouaillardet gilles@rist.or.jp

### CODE REVIEW

**Comment by ggouaillardet** [comment]
This feature can be needed when configure with VPATH
sources are in /.../src/project
and build is in /.../build/project
(cd /.../build/project && ../../src/project/configure && make install)
some projects automatically generate source files and/or links in the build dir,
so in this case, and from a genhtml point of view, there are two prefixes indeed.
note the prefix automatic detection (get_prefix) is unchanged and detects up to one prefix only.

**Comment by oberpar** [comment]
Could you rework the $cli_prefix handling command line parsing to work like \@opt_ignore_errors parsing? That is, use => \@dir_prefix in GetOptions and optionally split the array contents containing commas (like in parse_ignore_errors).

Also please post this commit including a descriptive log message and sign-off as patch to ltp-coverage@lists.sourceforge.net so that I can integrate it (cumbersome, I know, but required by our policy to document your code submission).

**Comment by ggouaillardet** [comment]
i updated this PR and posted the patch at http://sourceforge.net/p/ltp/mailman/message/34333968

**Comment by oberpar** [comment]
This was applied via a3572971367198ef0febe476052640bd09bec931. Closing.

**Pull request closed without merging**
