### PR TITLE
Handle --include and --exclude for inital captures

### PR DESCRIPTION
**Pull request by marc-groundctl**
This resolves issue #84 by changing `process_graphfile` to call `filter_source_files` (which handles the `--include` and `--exclude` options) instead of only checking if files are external.

### CODE REVIEW

**Comment by JeremyAgost** [comment]
Is there any reason this can't be merged? We'd like to use mainline lcov in our project but are still waiting on this to make it in.

**Comment by henry2cox** [comment]
FWIW:  I had implemented something like this - but added it as an option to genhtml, geninfo, and lcov (i.e., you can use it everywhere).  Also added an option to do regexp substitution on filenames at the same time (man pages explain why this is useful - but you may be using sed scripts and already know why you want it).
The branch contains quite a few other features as well - see PR #86 and the repo mentioned there.

**Comment by henry2cox** [comment]
As mentioned above:  I think this is included/subsumed by #169 - so this one can be closed once that one is merged.

**Comment by henry2cox** [comment]
Now that #169 is merged - could you take a quick look to verify whether your use model is properly supported now or not?
Please close the PR if we are good to go - or update the PR and/or open an issue if more needs to be done.
Thanks!
Henry

**Comment by henry2cox** [comment]
Good to hear.
Yes - there are a bunch of new error checks (including checks that the include/exclude patterns successfully applied to something (e.g., they don't appear to contain typos which make them useless).
Sounds like you found the controls to ignore or suppress the new checks.

**Comment by henry2cox** [comment]
I believe this PR has been subsumed/the desired functionality has been implemented - albeit, in a different way.
Closing this PR now.

If there is something missing or something that does not work as expected:  please open a new issue and/or a corresponding PR.
Henry

**Pull request closed without merging**
