### PR TITLE
minor fixups for `make check`

### PR DESCRIPTION
**Pull request by nega0**
- fix numeric compare in `tests/common.mk`
 - rename `tests/lcov/format/Makfile` → `tests/lcov/format/Makefile`
 - add test artifact to `make clean`
 - update `.gitignore` with new test artifacts

Signed-off-by: nega <nega0@users.noreply.github.com>

### CODE REVIEW

**Comment by henry2cox** [comment]
Thanks for the fixes.  Good to know that somebody read the code and/or the tests :-)

Sorry to be pedantic - but could you add a 'signed off by' line?
Or possibly it is there and I just can't see it.
Same comment applies to the other pull request.

Henry

**Comment by nega0** [comment]
sure. you squash merge, correct?

**Comment by henry2cox** [comment]
I believe so - but I fear that I am very far from an expert, so do not know for sure.

**Comment by nega0** [comment]
ok. sign offs are in the PR descriptions and the individual commits.

**Comment by henry2cox** [comment]
thanks....should be visible in master now (??)

**Pull request merged**
