### PR TITLE
add attributes for windows users

### PR DESCRIPTION
**Pull request by bollenn**
Add attributes file to make live of a windows user some easier

### CODE REVIEW

**Comment by SteinHeselmans** [comment]
:+1:

**Comment by oberpar** [comment]
Sorry for the delayed response. Could you re-submit with a commit message including a line or two on how this helps windows users and also a signed-off line according to the [Contribution guidelines](https://raw.githubusercontent.com/linux-test-project/lcov/master/CONTRIBUTING)? I'm assuming this doesn't help with source files without file extensions.

**Review by alhameli1 — CHANGES_REQUESTED** [review]
Changes

**Comment by GitMensch** [comment]
This is just something that is useful for people that check out the git repo on Windows, it says "check out any .sh file as text and with unix lf". As this isn't something I'd consider "copyrigthable" at all and it doesn't apply to much people and won't harm anybody else I suggest to either accept the PR or close it and do the commit yourself.

@oberpar What do you think?

**Comment by bollenn** [comment]
I've rebased and updated the commit comments....

**Comment by oberpar** [comment]
Added as 8c34f13587e1 ("lcov: Add file attributes for shell scripts") with minor changes.

Thank you for your contribution!

I've also added an explicit Signed-off line with your e-mail address assuming that your contribution was made under the terms described in [CONTRIBUTING](https://github.com/linux-test-project/lcov/blob/master/CONTRIBUTING). If you disagree with this explicit Signed-off, please let me know so I can revert this commit.

**Pull request closed without merging**
