### PR TITLE
Add simple CI based on GitHub Actions: run the test suite + ensure clean `make uninstall` + protect against introduction of new spelling errors

### PR DESCRIPTION
**Pull request by hartwork**
Sits on top of pull requests…

- ~#344~
- ~#345~
- ~#346~
- ~#352~

…and also a cheap workaround for issue #347… for a remote chance at a green CI, **for now**.

~However the CI is currently **red** because of broken tests (issue #343).~

It's fair to say that this pull request is ready to be reviewed ~but not (yet) to be merged~. I'm looking forward to your feedback! :pray:

### CODE REVIEW

**Comment by henry2cox** [comment]
I'm going to display some ignorance here (sorry).

I fixed (or believe I fixed) two of the 3 test fails you found (dumb errors on my part - hazards of working in multiple environments).
Still unsure about the last one (.../tests/py2lcov/py2lcov.sh) - which passes in my environment and which I can't seem to make fail.

Presuming I push my various fixes and merge this CI PR - will the tests run in a way that we will be able to see the shrapnel from failing tests?  Or how do you recommend to reproduce the issue so we can fix that one?

**Comment by hartwork** [comment]
Hello @henry2cox,

> I'm going to display some ignorance here (sorry).

your reply doesn't feel ignorant to me, no worries.

> I fixed (or believe I fixed) two of the 3 test fails you found (dumb errors on my part - hazards of working in multiple environments). Still unsure about the last one (.../tests/py2lcov/py2lcov.sh) - which passes in my environment and which I can't seem to make fail.

My branch `simple-github-actions-ci` sits on top of latest `master` (at 869e167c06b5b8f87c079824bf31fde4782aaa4d) so at least in `master` all of these 3 issues remain. I can prepare a `Dockerfile` for you to reproduce the issue, if you like. With luck I'll share that file in #343 in a few minutes.

> Presuming I push my various fixes and merge this CI PR - will the tests run in a way that we will be able to see the shrapnel from failing tests? Or how do you recommend to reproduce the issue so we can fix that one?

Besides the `Dockerfile` idea mentioned above, I recommend to start a new branch on top of mine here and push that to give the CI a chance report back on how the fixes are working. Or we merge the CI to `master` first: I made it so that it expects exactly 3 failures so CI will be green with status quo and we'll decrease the number down to 0 over time once things get fixed. The best approach would probably be to merge the CI first to be sure that we never put things on `master` that worsens status quo and the to only feed `master` from pull requests, including your own changes. instead of direct pushes to `master`. It's a few clicks more but it will make `master` be rock solid.

What do you think?

**Comment by hartwork** [comment]
@henry2cox PS: You can see at https://github.com/hartwork/lcov-fork/actions how this very CI looks and behaves in practice.

**Comment by henry2cox** [comment]
> What do you think?

Sounds like a good plan.
Just may take me a while to figure out the workflow.

**Comment by hartwork** [comment]
@henry2cox cool! Should we merge #352 first and I rebase onto latest `master`, after?

PS: There's probably a button "Approve" somewhere down here to let the CI run over here as well btw. It's not approving the pull request but the CI run.

**Comment by henry2cox** [comment]
> @henry2cox cool! Should we merge #352 first and I rebase onto latest `master`, after?

done.

**Comment by hartwork** [comment]
> > @henry2cox cool! Should we merge #352 first and I rebase onto latest `master`, after?
> 
> done.

@henry2cox thanks! Rebased and pushed.

**Comment by hartwork** [comment]
Woohoo! :tada:

**Comment by henry2cox** [comment]
Indeed.
Now for me to figure out how to stage the various fixes (and a few feature updates) using the new workflow.

**Comment by hartwork** [comment]
@henry2cox if you feel comfortable pushing them as a new branch, maybe having a look will give me an idea or two how to continue. Just an idea.

**Pull request merged**
